### ISSUE TITLE
User profile (general tab) flags (non-existing) parsing errors and does not allow saving

### ISSUE THREAD

**Issue by GwynethLlewelyn** [JordanKnott/project-citadel#168]
**Describe the bug**
When changing one's profile, the General tab, which has most (all?) of the information for the current user (including the avatar!), incorrectly flags missing/parsing errors on the many items, therefore refusing to save the profile (the button is disabled). There is no fix and no workaround.

The JavaScript error console is not very helpful; it only states `user required <UUID of the current user` which, as of commit 998db2a5da497a7902198a728ddc040fcacbacd6, refers to the error displayed on `Routes.tsx`, line 35. It looks like the React components are not receiving the information supplied via the form for the current user, but, then again, I don't know React, so I really have no idea about what is happening.

See also similar issues reported earlier, e.g. #158 or #152, where the visual feedback is similar (and may be related to the same underlying issue).

There are also some visual issues on the labels (they overlap the text fields). On other sections of Taskcafé, these labels have a small animation that puts them 'out of the way', but such animation is not present on this form (neither it is on the two issues above mentioned). That might be a consequence of the error thrown: JavaScript execution might have stopped due to an error, and the remaining code for the 'special effects' is not being called.

**Expected behavior**
1. While in some cases it's true that some information might be missing (or erroneous), when everything is correctly filled in, the profile form _should_ save all data.

2. The visual aspect of the labels should be consistent with the other panels where the small animation to get the field 'out of the way' is working.

**Screenshots / Live demo link**
Here is a screenshot from data which was manually entered in the database, and where I'm attempting to edit the **Bio** field. Note how there is a visual overlap of the label and the email field (which, btw, _is_ a correct and valid email address!)

<img width="1459" alt="Before editing" src="https://user-images.githubusercontent.com/304404/211407805-9a0717db-9fd5-45c2-b9ec-c883e454eccb.png">

After clicking on <kbd>Save Change</kbd> (shouldn't it be plural, btw?), here is what Taskcafé displays:

<img width="1459" alt="After editing" src="https://user-images.githubusercontent.com/304404/211408701-e686a022-6be5-409c-9a9f-3f31de9e9d26.png">

Note how the **Bio** field has, indeed, been changed; however, because the <kbd>Save Change</kbd> button is not working, nothing gets saved, and all changes are lost...

**Additional context**
Also note that all the information seen on my snapshots was manually added, directly on the database, and I mean **everything** (i.e. users, user avatars, organisation, teams, description fields on the user's profile, user membership [admin, member...] — even the bcrypt'ed password hash!), except for the project and its associated cards/tasks. Thus, the snapshots may give the false sensation that it is possible to add some information

I'd love to send any Taskcafé web service logs if I only knew how to extract them from Docker! 🤣

**Comment by 542154968** [comment]
![image](https://github.com/user-attachments/assets/ac20fb63-65ae-45c9-b1ff-a2e23b9bae9f)
一样的问题

**Comment by GwynethLlewelyn** [comment]
@542154968 I believe that the issue I mentioned almost two years ago (!) was actually fixed in the meantime. I haven't checked lately, but I think that's the case.

**Comment by 542154968** [comment]
> @542154968 I believe that the issue I mentioned almost two years ago (!) was actually fixed in the meantime. I haven't checked lately, but I think that's the case.

My colleague just built a new version using the latest Docker image yesterday, and the issue still exists. Unfortunately.

However, when I cloned the repository and ran the code locally, the form validation logic works fine. I suspect that the issue might be with the Docker image build or that the bug fix has not been updated in the Docker image.
![image](https://github.com/user-attachments/assets/62f7a648-4615-4c76-86bf-7302376c60b9)

**Comment by GwynethLlewelyn** [comment]
Ah!... that could very well be the case. Since I don't use Docker myself, I can't tell.
